# Generate cacert.pem from Windows certificate store

###############################################################################################
# No cacert.pem
###############################################################################################
#
# C:\OpenSSL-Win64>set SSL_CERT_FILE=
# C:\OpenSSL-Win64>bin\openssl s_client -connect www.google.com:443 -tls1
# CONNECTED(000001C0)
# depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
# verify error:num=20:unable to get local issuer certificate
# ---
# Certificate chain
#  0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=www.google.com
#    i:/C=US/O=Google Inc/CN=Google Internet Authority G2
#  1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
#    i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
#  2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
#    i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
# ---
# Server certificate
# -----BEGIN CERTIFICATE-----
# MIIEgDCCA2igAwIBAgIIVOtqwO6+oEswDQYJKoZIhvcNAQELBQAwSTELMAkGA1UE
# BhMCVVMxEzARBgNVBAoTCkdvb2dsZSBJbmMxJTAjBgNVBAMTHEdvb2dsZSBJbnRl
# cm5ldCBBdXRob3JpdHkgRzIwHhcNMTcwNTI0MTczOTE1WhcNMTcwODE2MTcxMzAw
# WjBoMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwN
# TW91bnRhaW4gVmlldzETMBEGA1UECgwKR29vZ2xlIEluYzEXMBUGA1UEAwwOd3d3
# Lmdvb2dsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7lLfe
# Dp1TFViBN0Og3r290njkdwTcmCl/Vqst6fKdvzwAKl4CSlE+FzJ0F9/VBKcwYczD
# b88GCeUnu1RfG9XYcDm2lQDIyge1gv6ULyZcnzsYlg1ih2C09I1xKSdNxr7PqR2q
# Hcrru4qGqYa2F163ViCSpAWp3GgTk3yLIc56i0xcoLkLBELocLi12jvu+ejmepri
# ctzWWl8XT4sbjUxlbmQUc8fwwfMf+xIVmQqEWLc+HXS+mZp6cKi67I+UvWdQbqmm
# 18n1vRp6Bybc8Beph5BynoeNchwSSQw6nBkxIoxv1VgOCCM5HMKZB7NHzTh8iZhz
# Ln0cS6zdT+cFeGiJAgMBAAGjggFLMIIBRzAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
# KwYBBQUHAwIwGQYDVR0RBBIwEIIOd3d3Lmdvb2dsZS5jb20waAYIKwYBBQUHAQEE
# XDBaMCsGCCsGAQUFBzAChh9odHRwOi8vcGtpLmdvb2dsZS5jb20vR0lBRzIuY3J0
# MCsGCCsGAQUFBzABhh9odHRwOi8vY2xpZW50czEuZ29vZ2xlLmNvbS9vY3NwMB0G
# A1UdDgQWBBRQcE7Z5LNtVxRg5a7LyUjonjTYcTAMBgNVHRMBAf8EAjAAMB8GA1Ud
# IwQYMBaAFErdBhYbvPZotXb1gba7Yhq6WoEvMCEGA1UdIAQaMBgwDAYKKwYBBAHW
# eQIFATAIBgZngQwBAgIwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL3BraS5nb29n
# bGUuY29tL0dJQUcyLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAZ16atylKGgS3f2EZ
# EYLfj/esSBJlHXiAMIeevH1NBGFlXUkF9EfAXNTf5U7iDc45oF+wradmJjb6Amhc
# UQKY4tWdXbOFwU/M3k8wWbG/WtDno9bD4mER+BvltixxIG9I5mGmp2YHNmxCRD/q
# MohfvILavTXx9ObMDPAjxwjUk/WceeQJfKV+pUCQmhXVwTToysaTAzvpaTSpiK5F
# 35+M6cD3HvX45khUVYFpqRTNjVeiKf8ZY3m/205OrxkkaXWnUgMdgKAaua6OItoZ
# fFvGQ6qrbCpKImuNArCuI391XyQfphTF2USIBwK52UziGoILxSXi5rJpQCjRl0js
# Fnlr1g==
# -----END CERTIFICATE-----
# subject=/C=US/ST=California/L=Mountain View/O=Google Inc/CN=www.google.com
# issuer=/C=US/O=Google Inc/CN=Google Internet Authority G2
# ---
# No client certificate CA names sent
# Server Temp Key: ECDH, P-256, 256 bits
# ---
# SSL handshake has read 3789 bytes and written 333 bytes
# ---
# New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-SHA
# Server public key is 2048 bit
# Secure Renegotiation IS supported
# Compression: NONE
# Expansion: NONE
# No ALPN negotiated
# SSL-Session:
#     Protocol  : TLSv1
#     Cipher    : ECDHE-RSA-AES128-SHA
#     Session-ID: A6E4221CA4766BE7C18105A372BED4ABA022CF2023D1E6598554949162B4A412
#     Session-ID-ctx:
#     Master-Key: 6BB5B5B36A0BC26BBD2840B1508DEF6439DD6BE7CE585DBA2709E3DF7140D0BABE6231478F9FDC97670FB0F90885FADA
#     Key-Arg   : None
#     PSK identity: None
#     PSK identity hint: None
#     SRP username: None
#     TLS session ticket lifetime hint: 100800 (seconds)
#     TLS session ticket:
#     0000 - ca 43 a5 43 7e c8 a8 89-6d c7 73 71 6b d9 ec 09   .C.C~...m.sqk...
#     0010 - 96 7a 31 98 78 50 3b 26-16 b3 ec 4e c4 81 12 5c   .z1.xP;&...N...\
#     0020 - 92 69 21 62 f8 42 49 a9-e3 41 e1 ae 4f 27 cf 56   .i!b.BI..A..O'.V
#     0030 - f3 59 73 81 68 ce e2 d8-9b 5a 52 e8 84 54 44 53   .Ys.h....ZR..TDS
#     0040 - 15 cd fb f5 b4 87 c4 6f-8b 11 03 6c 46 b3 fb 71   .......o...lF..q
#     0050 - e5 61 b9 8c cc f5 ad b3-ff 4e b3 b3 ff ba 1a 5b   .a.......N.....[
#     0060 - f6 7b e1 a2 9c 91 fa 34-46 0b f8 41 f2 d0 86 af   .{.....4F..A....
#     0070 - 3a 2d 8e 81 95 dc 68 aa-e7 ea cc 24 93 e4 92 ef   :-....h....$....
#     0080 - ab 59 a5 21 e7 f8 15 35-05 ee 7a 74 95 65 8d 8f   .Y.!...5..zt.e..
#     0090 - 84 fe 95 45 61 e1 f5 a9-59 2e 56 ba a1 a5 2f d1   ...Ea...Y.V.../.
#     00a0 - 90 c6 8b 8d                                       ....

#     Start Time: 1496799192
#     Timeout   : 7200 (sec)
#     Verify return code: 20 (unable to get local issuer certificate)
# ---
# read:errno=10093
#
###############################################################################################
# With cacert.pem generated by this script
###############################################################################################
# C:\OpenSSL-Win64>set SSL_CERT_FILE=C:\OpenSSL-Win64\certs\cacert.pem
# C:\OpenSSL-Win64>bin\openssl s_client -connect www.google.com:443 -tls1
# CONNECTED(000001E8)
# depth=3 C = US, O = Equifax, OU = Equifax Secure Certificate Authority
# verify return:1
# depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
# verify return:1
# depth=1 C = US, O = Google Inc, CN = Google Internet Authority G2
# verify return:1
# depth=0 C = US, ST = California, L = Mountain View, O = Google Inc, CN = www.google.com
# verify return:1
# ---
# Certificate chain
#  0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=www.google.com
#    i:/C=US/O=Google Inc/CN=Google Internet Authority G2
#  1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
#    i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
#  2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
#    i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
# ---
# Server certificate
# -----BEGIN CERTIFICATE-----
# MIIEgDCCA2igAwIBAgIIVOtqwO6+oEswDQYJKoZIhvcNAQELBQAwSTELMAkGA1UE
# BhMCVVMxEzARBgNVBAoTCkdvb2dsZSBJbmMxJTAjBgNVBAMTHEdvb2dsZSBJbnRl
# cm5ldCBBdXRob3JpdHkgRzIwHhcNMTcwNTI0MTczOTE1WhcNMTcwODE2MTcxMzAw
# WjBoMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwN
# TW91bnRhaW4gVmlldzETMBEGA1UECgwKR29vZ2xlIEluYzEXMBUGA1UEAwwOd3d3
# Lmdvb2dsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7lLfe
# Dp1TFViBN0Og3r290njkdwTcmCl/Vqst6fKdvzwAKl4CSlE+FzJ0F9/VBKcwYczD
# b88GCeUnu1RfG9XYcDm2lQDIyge1gv6ULyZcnzsYlg1ih2C09I1xKSdNxr7PqR2q
# Hcrru4qGqYa2F163ViCSpAWp3GgTk3yLIc56i0xcoLkLBELocLi12jvu+ejmepri
# ctzWWl8XT4sbjUxlbmQUc8fwwfMf+xIVmQqEWLc+HXS+mZp6cKi67I+UvWdQbqmm
# 18n1vRp6Bybc8Beph5BynoeNchwSSQw6nBkxIoxv1VgOCCM5HMKZB7NHzTh8iZhz
# Ln0cS6zdT+cFeGiJAgMBAAGjggFLMIIBRzAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
# KwYBBQUHAwIwGQYDVR0RBBIwEIIOd3d3Lmdvb2dsZS5jb20waAYIKwYBBQUHAQEE
# XDBaMCsGCCsGAQUFBzAChh9odHRwOi8vcGtpLmdvb2dsZS5jb20vR0lBRzIuY3J0
# MCsGCCsGAQUFBzABhh9odHRwOi8vY2xpZW50czEuZ29vZ2xlLmNvbS9vY3NwMB0G
# A1UdDgQWBBRQcE7Z5LNtVxRg5a7LyUjonjTYcTAMBgNVHRMBAf8EAjAAMB8GA1Ud
# IwQYMBaAFErdBhYbvPZotXb1gba7Yhq6WoEvMCEGA1UdIAQaMBgwDAYKKwYBBAHW
# eQIFATAIBgZngQwBAgIwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL3BraS5nb29n
# bGUuY29tL0dJQUcyLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAZ16atylKGgS3f2EZ
# EYLfj/esSBJlHXiAMIeevH1NBGFlXUkF9EfAXNTf5U7iDc45oF+wradmJjb6Amhc
# UQKY4tWdXbOFwU/M3k8wWbG/WtDno9bD4mER+BvltixxIG9I5mGmp2YHNmxCRD/q
# MohfvILavTXx9ObMDPAjxwjUk/WceeQJfKV+pUCQmhXVwTToysaTAzvpaTSpiK5F
# 35+M6cD3HvX45khUVYFpqRTNjVeiKf8ZY3m/205OrxkkaXWnUgMdgKAaua6OItoZ
# fFvGQ6qrbCpKImuNArCuI391XyQfphTF2USIBwK52UziGoILxSXi5rJpQCjRl0js
# Fnlr1g==
# -----END CERTIFICATE-----
# subject=/C=US/ST=California/L=Mountain View/O=Google Inc/CN=www.google.com
# issuer=/C=US/O=Google Inc/CN=Google Internet Authority G2
# ---
# No client certificate CA names sent
# Server Temp Key: ECDH, P-256, 256 bits
# ---
# SSL handshake has read 3789 bytes and written 333 bytes
# ---
# New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-SHA
# Server public key is 2048 bit
# Secure Renegotiation IS supported
# Compression: NONE
# Expansion: NONE
# No ALPN negotiated
# SSL-Session:
#     Protocol  : TLSv1
#     Cipher    : ECDHE-RSA-AES128-SHA
#     Session-ID: 28E169F762E8C843AACE8505145D6119BF1071A8858CA8739ED91A16A73C847E
#     Session-ID-ctx:
#     Master-Key: 8BB122D2DC05DD0BF52D7CC6B349A7FE514530D58814F7F08A688D9A93EF5A66A212AFE924F6459B9E4AA25A001F6C0B
#     Key-Arg   : None
#     PSK identity: None
#     PSK identity hint: None
#     SRP username: None
#     TLS session ticket lifetime hint: 100800 (seconds)
#     TLS session ticket:
#     0000 - ca 43 a5 43 7e c8 a8 89-6d c7 73 71 6b d9 ec 09   .C.C~...m.sqk...
#     0010 - 48 1d c2 b9 6b b3 98 6c-41 be 1b 86 d9 1f b3 af   H...k..lA.......
#     0020 - a8 77 ff 68 87 9f c1 a2-bc 60 27 75 26 ad e5 0b   .w.h.....`'u&...
#     0030 - 4f 3c 64 ac 31 66 97 ea-f5 72 73 83 70 f4 81 09   O<d.1f...rs.p...
#     0040 - 81 22 1c 77 16 90 02 c5-73 97 5c 4e 6b 34 40 6e   .".w....s.\Nk4@n
#     0050 - 52 22 e9 24 91 c7 ab 49-22 82 cc 16 5e 9b 40 0c   R".$...I"...^.@.
#     0060 - ca 93 20 03 60 96 f9 6c-d4 5d 23 24 ee 4c 37 d1   .. .`..l.]#$.L7.
#     0070 - 7c a0 0c 3f 29 b0 b3 77-99 bf 45 28 26 e0 a6 c7   |..?)..w..E(&...
#     0080 - 5c 2d 4b d4 46 81 83 b2-13 3c fb c0 98 14 ca 00   \-K.F....<......
#     0090 - 36 a0 6f 8e 03 32 4f 3c-7b 9c 45 5e ad f7 90 ff   6.o..2O<{.E^....
#     00a0 - 24 7d 45 97                                       $}E.

#     Start Time: 1496799159
#     Timeout   : 7200 (sec)
#     Verify return code: 0 (ok)
# ---
# read:errno=10093

Get-ChildItem -path cert:\LocalMachine\AuthRoot | ForEach-Object {
    $all += $_.FriendlyName
    $all += "`n"
    $all += "=" * $_.FriendlyName.length
    $all += "`n"
    $all += "-----BEGIN CERTIFICATE-----`n"
    $der = $_.export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert)
    $all += [System.Convert]::ToBase64String($der, [System.Base64FormattingOptions]::InsertLineBreaks)
    $all += "`n-----END CERTIFICATE-----`n`n"
}

$all